// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfyuzxacadhygyqptdjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmeXV6eGFjYWRoeWd5cXB0ZGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTE3MDQsImV4cCI6MjA3MTI4NzcwNH0.hiqMqeYfjpXBqRNraKDcAunG1sD_2L8fzYEFanz2Gdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});